const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const sharp=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const fs=require('fs'),assert=require('node:assert/strict');
const out='artifacts/screenshot-recognition/',origin='http://127.0.0.1:8765/';
const originals=['31df9e26-2a65-4acb-827e-e32ad1b4c422','5bb472be-4b93-4283-93f1-070bb90a1c50','2c8eed9a-8910-414c-b5a9-db7ba74e2288','3724b03b-e275-45db-aa09-c513f57589e4','2438614b-1bbf-4250-8f03-2017572adcf8'].map(id=>'C:/Users/user/AppData/Local/Temp/codex-clipboard-'+id+'.png');
(async()=>{
 await sharp('image/screenshot-examples/panel.png').jpeg({quality:90}).toFile(out+'panel.jpg');await sharp('image/screenshot-examples/panel.png').webp().toFile(out+'panel.webp');await sharp('image/screenshot-examples/full.png').resize(480).blur(3).png().toFile(out+'blurred.png');
 const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],posts=[];
 const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});
 const open=async(p,lang='zh-TW',extra='')=>{await p.goto(origin+'register-workspace.html?view=register&mode=library&lang='+lang+extra);await p.locator('[data-library-add]').click();await p.locator('[data-library-screenshot]').click();};
 const upload=async(p,files,count)=>{await p.locator('[data-ocr-files]').setInputFiles(files);await p.waitForFunction(count=>document.querySelectorAll('[data-ocr-item]').length===count&&!document.querySelector('[data-ocr-files]').disabled,count,{timeout:180000});};
 const fields=async p=>p.locator('[data-ocr-item]').evaluateAll(items=>items.map(item=>({name:item.querySelector('form p').textContent,fields:Object.fromEntries(Array.from(item.querySelectorAll('[data-ocr-field]')).map(e=>[e.dataset.ocrField,e.value]))})));
 await open(page);const baseline=await page.evaluate(()=>localStorage.getItem('mcData'));await upload(page,originals,5);let actual=await fields(page);assert.deepEqual(actual.map(r=>r.fields.detectedCost),['4','3','3','1','1']);assert.equal(actual[0].fields.catalogId,'181');assert.equal(actual[1].fields.catalogId,'184');assert.equal(actual[2].fields.catalogId,'183');assert.equal(actual[3].fields.catalogId,'186');assert.equal(actual[4].fields.catalogId,'');
 const expectedStats=[[['crit_rate',7.5],['atk_flat',30],['resonance_skill_damage',9.4],['heavy_attack_damage',10.1],['def_flat',40]],[['def_percent',8.1],['crit_rate',6.3],['crit_damage',18.6],['resonance_skill_damage',10.9],['hp_percent',7.9]],[['hp_flat',470],['def_percent',9],['resonance_skill_damage',6.4],['crit_rate',10.5],['basic_attack_damage',7.9]],[['resonance_efficiency',10],['resonance_skill_damage',10.1],['crit_damage',15],['resonance_liberation_damage',10.1],['crit_rate',7.5]],[['hp_flat',470],['crit_damage',15],['def_flat',40],['atk_percent',10.1],['crit_rate',6.3]]];
 actual.forEach((r,i)=>{assert.equal(Number(r.fields['main.value']),[44,30,30,18,18][i]);expectedStats[i].forEach(([key,value],j)=>{if(r.fields['sub'+j+'.key'])assert.equal(r.fields['sub'+j+'.key'],key);if(r.fields['sub'+j+'.value'])assert.equal(Number(r.fields['sub'+j+'.value']),value);});});assert.equal(await page.evaluate(()=>localStorage.getItem('mcData')),baseline);fs.writeFileSync(out+'actual-results.json',JSON.stringify(actual,null,2));console.log('PASS original full-screen batch: five results, four catalog matches, unknown catalog remains blank, zero writes');
 await upload(page,[originals[0]],5);assert.match(await page.locator('[data-ocr-progress]').textContent(),/重複/);assert.equal(await page.evaluate(()=>localStorage.getItem('mcData')),baseline);
 // 验收截图使用已遮码副本，原图只参与识别与数值断言。
 await page.locator('[data-ocr-item] img').evaluateAll(imgs=>imgs.forEach((img,i)=>img.src='/image/screenshot-examples/'+(i===0?'full':'full-'+(i+1))+'.png'));
 await page.locator('[data-ocr-item]').nth(1).screenshot({path:out+'desktop-review.png'});await page.screenshot({path:out+'desktop-batch.png'});
 const first=page.locator('[data-ocr-item]').first();await first.locator('[data-ocr-field="sub0.key"]').selectOption('crit_rate');await first.locator('[data-ocr-field="sub0.value"]').selectOption('7.5');await first.locator('[data-ocr-field="sub0.value"]').blur();await first.locator('[data-ocr-confirm]').check();assert.equal(await page.evaluate(()=>localStorage.getItem('mcData')),baseline);await first.locator('button[type=submit]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('mcData')).unusedEchoes?.length===1);let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mcData')));assert.equal(saved.unusedEchoes[0].costListId,181);assert.equal(saved.unusedEchoes[0].propertyList.length,5);assert.equal(saved.unusedEchoes[0].mainAtrri,'暴伤44%');assert.ok(!JSON.stringify(saved).includes('blob:'));await first.locator('img').evaluate(img=>img.src='/image/screenshot-examples/full.png');await first.screenshot({path:out+'desktop-saved.png'});console.log('PASS correction + explicit confirmation + existing Core library save');
 await page.goto(origin+'register-workspace.html?view=register&mode=library');await page.screenshot({path:out+'desktop-library.png'});
 for(const [index,lang] of ['zh-TW','zh-CN','en'].entries()){
  await open(page,lang);await page.screenshot({path:out+'desktop-'+lang+'-upload.png'});await page.locator('[data-ocr-examples]').click();await page.screenshot({path:out+'desktop-'+lang+'-examples.png'});await page.locator('[data-ocr-examples]').click();
  const before=await page.evaluate(()=>localStorage.getItem('mcData'));await upload(page,[index===0?'image/screenshot-examples/panel.png':out+(index===1?'panel.jpg':'panel.webp')],1);actual=await fields(page);assert.equal(actual[0].fields.detectedCost,'1');assert.equal(actual[0].fields['main.value'],'18');assert.equal(await page.evaluate(()=>localStorage.getItem('mcData')),before);await page.locator('[data-ocr-item]').screenshot({path:out+'desktop-'+lang+'-crop.png'});
  await page.setViewportSize({width:390,height:844});await page.locator('[data-library-screenshot-back]').scrollIntoViewIfNeeded();await page.screenshot({path:out+'mobile-'+lang+'-upload.png'});await page.locator('[data-ocr-item] form').scrollIntoViewIfNeeded();await page.screenshot({path:out+'mobile-'+lang+'-review.png'});await page.locator('[data-ocr-item] button[type=submit]').scrollIntoViewIfNeeded();await page.screenshot({path:out+'mobile-'+lang+'-confirm.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(!(await page.locator('.rw-ocr').textContent()).includes('[screenshot.'));await page.setViewportSize({width:1440,height:1100});console.log('PASS '+lang+' Desktop/Mobile, panel crop '+['PNG','JPEG','WEBP'][index]);
 }
 await open(page);const beforeBad=await page.evaluate(()=>localStorage.getItem('mcData'));await upload(page,[out+'incomplete.png',out+'blurred.png',out+'desktop-zh-TW-upload.png'],3);actual=await fields(page);assert.ok(actual.every(r=>!r.fields.catalogId));assert.ok(actual[0].fields['main.value']==='');assert.equal(await page.evaluate(()=>localStorage.getItem('mcData')),beforeBad);await page.locator('[data-ocr-item]').first().screenshot({path:out+'incomplete-review.png'});console.log('PASS incomplete, blurred and wrong-page images remain unsaved / unknown');
 await upload(page,[{name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('not an image')}],4);assert.match(await page.locator('[data-ocr-item]').last().textContent(),/無法讀取/);
 await open(page);await upload(page,['image/screenshot-examples/panel.png'],1);await page.evaluate(()=>{const d=JSON.parse(localStorage.getItem('mcData'));d.pjLevel=42;localStorage.setItem('mcData',JSON.stringify(d));});const stale=page.locator('[data-ocr-item]');await stale.locator('[data-ocr-field="catalogId"]').selectOption('186');await stale.locator('[data-ocr-confirm]').check();await stale.locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mcData')).unusedEchoes.length),1);assert.equal(await page.locator('[data-ocr-refresh]').count(),1);console.log('PASS stale data blocks commit');
 await page.evaluate(()=>{const d=JSON.parse(localStorage.getItem('mcData'));d.role=[CharacterCore.createRole(roleList[0],101),{...CharacterCore.createRole(roleList[0],102),isImport:true}];localStorage.setItem('mcData',JSON.stringify(d));});await open(page,'zh-TW','&roleid=101');await upload(page,['image/screenshot-examples/panel.png'],1);const roleItem=page.locator('[data-ocr-item]');assert.equal(await roleItem.locator('[data-ocr-target]').inputValue(),'');await roleItem.locator('[data-ocr-target]').selectOption('101');await roleItem.locator('[data-ocr-confirm]').check();await roleItem.locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mcData')).role[0].costList.length),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mcData')).role[1].costList.length),0);await page.screenshot({path:out+'role-context-saved.png'});await open(page,'zh-TW','&roleid=102');await upload(page,['image/screenshot-examples/panel.png'],1);assert.equal(await page.locator('[data-ocr-target] option').count(),1);console.log('PASS explicit role-context append, default library destination, imported roles remain read-only');
 const engineContext=await browser.newContext();const unavailable=await engineContext.newPage();await unavailable.route('**/library/ocr/**',r=>r.abort());await open(unavailable);await upload(unavailable,['image/screenshot-examples/panel.png'],1);assert.match(await unavailable.locator('[data-ocr-item]').textContent(),/無法完成本機辨識/);assert.equal(await unavailable.evaluate(()=>localStorage.getItem('mcData')),null);await engineContext.close();console.log('PASS unavailable OCR resources: manual review available, no writes');
 assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);fs.writeFileSync(out+'browser-test-result.json',JSON.stringify({passed:true,errors,posts,locales:['zh-TW','zh-CN','en'],sizes:['1440x1100','390x844']},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
